'use client'

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SolanaWalletProvider } from "../components/SolanaWalletProvider";
import { EthereumWalletProvider } from "../components/EthereumWalletProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// commented out so we can do 'use client'. without 'use client', there'd be an error due to a server-side dependency that is not accessible from the wallet provider
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <EthereumWalletProvider>
          <SolanaWalletProvider>
            {children}
          </SolanaWalletProvider>
        </EthereumWalletProvider>
      </body>
    </html>
  );
}

